// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanManager.Infrastructure.Data;

#nullable disable

namespace PlanManager.Infrastructure.Migrations
{
    [DbContext(typeof(PlanManagerDbContext))]
    [Migration("20250718191430_AlterTablePlanPermissionRelation")]
    partial class AlterTablePlanPermissionRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.6.25358.103")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlanManager.Domain.Entities.Plan.Plan", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("IdCompany")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar")
                        .HasColumnName("IdCompany");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.ToTable("Plan", (string)null);
                });

            modelBuilder.Entity("PlanManager.Domain.Entities.Plan.PlanPermission", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("IdCompany")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar")
                        .HasColumnName("IdCompany");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.ToTable("PlanPermission", (string)null);
                });

            modelBuilder.Entity("PlanManager.Domain.Entities.Plan.PlanPermissionRelation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("IdPlan")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Plan");

                    b.Property<string>("IdPlanPermission")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PlanPermission");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("IdPlan");

                    b.HasIndex("IdPlanPermission");

                    b.ToTable("PlanPermissionRelation", (string)null);
                });

            modelBuilder.Entity("PlanManager.Domain.Entities.Profiles.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("PlanManager.Domain.Entities.Profiles.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("IdPerson")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar")
                        .HasColumnName("IdPerson");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar")
                        .HasColumnName("Password");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("IdPerson")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("PlanManager.Domain.Entities.Utils.LogActivity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Action");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar")
                        .HasColumnName("ObjectId");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar")
                        .HasColumnName("User");

                    b.HasKey("Id");

                    b.HasIndex("User");

                    b.ToTable("LogActivity", (string)null);
                });

            modelBuilder.Entity("PlanManager.Domain.Entities.Plan.Plan", b =>
                {
                    b.HasOne("PlanManager.Domain.Entities.Profiles.Person", "Company")
                        .WithMany()
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Plan_Person_PersonId");

                    b.OwnsOne("PlanManager.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<string>("PlanId")
                                .HasColumnType("nvarchar(11)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar")
                                .HasColumnName("Name");

                            b1.HasKey("PlanId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Plan");

                            b1.WithOwner()
                                .HasForeignKey("PlanId");
                        });

                    b.OwnsOne("PlanManager.Domain.ValueObjects.Value", "Value", b1 =>
                        {
                            b1.Property<string>("PlanId")
                                .HasColumnType("nvarchar(11)");

                            b1.Property<decimal>("ValueWith2Digits")
                                .HasColumnType("decimal")
                                .HasColumnName("Value");

                            b1.HasKey("PlanId");

                            b1.ToTable("Plan");

                            b1.WithOwner()
                                .HasForeignKey("PlanId");
                        });

                    b.Navigation("Company");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("PlanManager.Domain.Entities.Plan.PlanPermission", b =>
                {
                    b.HasOne("PlanManager.Domain.Entities.Profiles.Person", "Company")
                        .WithMany()
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlanPermission_Company");

                    b.OwnsOne("PlanManager.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<string>("PlanPermissionId")
                                .HasColumnType("nvarchar(11)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar")
                                .HasColumnName("Name");

                            b1.HasKey("PlanPermissionId");

                            b1.ToTable("PlanPermission");

                            b1.WithOwner()
                                .HasForeignKey("PlanPermissionId");
                        });

                    b.OwnsOne("PlanManager.Domain.ValueObjects.PermissionCode", "Code", b1 =>
                        {
                            b1.Property<string>("PlanPermissionId")
                                .HasColumnType("nvarchar(11)");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(28)
                                .HasColumnType("nvarchar")
                                .HasColumnName("Code");

                            b1.HasKey("PlanPermissionId");

                            b1.HasIndex("Code")
                                .IsUnique();

                            b1.ToTable("PlanPermission");

                            b1.WithOwner()
                                .HasForeignKey("PlanPermissionId");
                        });

                    b.Navigation("Code")
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("PlanManager.Domain.Entities.Plan.PlanPermissionRelation", b =>
                {
                    b.HasOne("PlanManager.Domain.Entities.Plan.Plan", "Plan")
                        .WithMany("Permissions")
                        .HasForeignKey("IdPlan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlanPermissionRelation_Plan_PlanId");

                    b.HasOne("PlanManager.Domain.Entities.Plan.PlanPermission", "PlanPermission")
                        .WithMany("Plans")
                        .HasForeignKey("IdPlanPermission")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlanPermissionRelation_PlanPermission_PlanPermissionId");

                    b.Navigation("Plan");

                    b.Navigation("PlanPermission");
                });

            modelBuilder.Entity("PlanManager.Domain.Entities.Profiles.Person", b =>
                {
                    b.OwnsOne("PlanManager.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<string>("PersonId")
                                .HasColumnType("nvarchar(11)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar")
                                .HasColumnName("City");

                            b1.Property<string>("Complement")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar")
                                .HasColumnName("Complement");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar")
                                .HasColumnName("Country");

                            b1.Property<bool>("HasHouseNumber")
                                .HasColumnType("bit")
                                .HasColumnName("HasHouseNumber");

                            b1.Property<string>("HouseNumber")
                                .HasColumnType("nvarchar")
                                .HasColumnName("HouseNumber");

                            b1.Property<string>("Neighboorhood")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar")
                                .HasColumnName("Neighboorhood");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar")
                                .HasColumnName("State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar")
                                .HasColumnName("Street");

                            b1.Property<string>("Zipcode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar")
                                .HasColumnName("Zipcode");

                            b1.HasKey("PersonId");

                            b1.ToTable("Person");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.OwnsOne("PlanManager.Domain.ValueObjects.Document", "Document", b1 =>
                        {
                            b1.Property<string>("PersonId")
                                .HasColumnType("nvarchar(11)");

                            b1.Property<string>("Identification")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("nvarchar")
                                .HasColumnName("Document");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("nvarchar")
                                .HasColumnName("Type");

                            b1.HasKey("PersonId");

                            b1.HasIndex("Identification")
                                .IsUnique();

                            b1.ToTable("Person");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.OwnsOne("PlanManager.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<string>("PersonId")
                                .HasColumnType("nvarchar(11)");

                            b1.Property<string>("EmailAddress")
                                .IsRequired()
                                .HasColumnType("nvarchar")
                                .HasColumnName("EmailAddress");

                            b1.HasKey("PersonId");

                            b1.HasIndex("EmailAddress")
                                .IsUnique();

                            b1.ToTable("Person");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.OwnsOne("PlanManager.Domain.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<string>("PersonId")
                                .HasColumnType("nvarchar(11)");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar")
                                .HasColumnName("LastName");

                            b1.HasKey("PersonId");

                            b1.ToTable("Person");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.OwnsOne("PlanManager.Domain.ValueObjects.Phone", "Phone", b1 =>
                        {
                            b1.Property<string>("PersonId")
                                .HasColumnType("nvarchar(11)");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("nvarchar")
                                .HasColumnName("CountryCode");

                            b1.Property<string>("DDD")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("nvarchar")
                                .HasColumnName("DDD");

                            b1.Property<string>("NumberWithDigit")
                                .IsRequired()
                                .HasMaxLength(9)
                                .HasColumnType("nvarchar")
                                .HasColumnName("PhoneNumberWithDigit");

                            b1.HasKey("PersonId");

                            b1.ToTable("Person");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Document")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();
                });

            modelBuilder.Entity("PlanManager.Domain.Entities.Profiles.User", b =>
                {
                    b.HasOne("PlanManager.Domain.Entities.Profiles.Person", "Person")
                        .WithOne()
                        .HasForeignKey("PlanManager.Domain.Entities.Profiles.User", "IdPerson")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_User_Person");

                    b.OwnsOne("PlanManager.Domain.ValueObjects.Username", "Username", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("nvarchar(11)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar")
                                .HasColumnName("Username");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Person");

                    b.Navigation("Username")
                        .IsRequired();
                });

            modelBuilder.Entity("PlanManager.Domain.Entities.Utils.LogActivity", b =>
                {
                    b.HasOne("PlanManager.Domain.Entities.Profiles.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LogActivity_User");

                    b.OwnsOne("PlanManager.Domain.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<string>("LogActivityId")
                                .HasColumnType("nvarchar(11)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar")
                                .HasColumnName("Description");

                            b1.HasKey("LogActivityId");

                            b1.ToTable("LogActivity");

                            b1.WithOwner()
                                .HasForeignKey("LogActivityId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("FromUser");
                });

            modelBuilder.Entity("PlanManager.Domain.Entities.Plan.Plan", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("PlanManager.Domain.Entities.Plan.PlanPermission", b =>
                {
                    b.Navigation("Plans");
                });
#pragma warning restore 612, 618
        }
    }
}
